
[path_nuker]
	check_route_blocks = true
	nuker_block_detection_system = 1
	nuker_type = 0
	nuker_bps = 40

[tp-settings]
	re-teleport = false
	re-tp_amount_of_times = 1
	smoothlook = 109
	ping_mode = 1
	aotv_teleport_time = 300
	aotv_wait_time = 458
	"look_time_(in_ms)" = 102

[main]
	top-to-bottom = false
	"replace_block_command_(after_editing_do_/ct_load)" = "replaceBlock"
	clear_command = "clear"
	linesqol = true
	distance_to_the_esp_block = 20
	nuker_type = 0
	aotv_teleport_time = 504
	nuker_bps = 40
	wait_on_first_point = false
	"clear_command_(after_editing_do_/ct_load)" = "clear"
	menu_keybind = true
	telport_if_cant_break = false
	rotation_angle = 100
	skip_vein_time = 10000
	beplace_block_command = "replaceBlock"
	block_on_route_esp = true
	render_pathbreak_helper = false
	structure_finder = false
	ignore_panes = true
	add_block_to_list_keybind = true
	check_route_blocks = true
	smoothlook = 5
	nuker_block_detection_system = 1
	wait_on_first_point_wait_time = 0
	macro_spot = 0

[helper-mode]
	turn_on_helper = true

[fail-safes]
	player_failsafe = false
	player_esp_distance_ = 135
	player_esp = false
	distance = 50
	actually_switch_to_aotv = false

[fun]
	block_esp_color_blue = 0
	open_gui_text = false
	ignore_panes = true
	render_block-to-block_lines = true
	actually_switch_to_aotv = true
	block_esp_color_green = 0
	new_dillo_head_movement = false
	"turn_on/off" = false
	block_esp_color_red = 10

[structure-finder]
	structure_finder = false

